import "../../styles/globals.css"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from "../../components/Navbar"
import React from "react"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function PageLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
<>
        {children}
</>
  )
}
